spring.application.name=blog1
spring.mongodb.database=blogDB
spring.data.mongodb.uri=mongodb://localhost:27017/blogDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration